# Generated by Django 6.0.5 on 2026-05-26 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_logged_in', 'User Logged In'), ('user_logged_out', 'User Logged Out'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('task_status_changed', 'Task Status Changed'), ('task_deleted', 'Task Deleted'), ('visit_created', 'Visit Created'), ('visit_started', 'Visit Started'), ('visit_notes_added', 'Visit Notes Added'), ('visit_completed', 'Visit Completed'), ('visit_cancelled', 'Visit Cancelled'), ('ai_output_generated', 'AI Output Generated')], db_index=True, max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=36)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
